import { z } from "zod";
import { LEARNING_TITLE_CHARACTER_LIMIT } from "@/lib/learning/title-limits";
import { resolveLearningIntent } from "@/lib/learning/learning-intent";
import { CORE_METHOD_IDS } from "@/lib/learning/method-catalog";
import { AgencyMethodRequestResolutionSchema } from "@/lib/study-route/agency-mode-controller";
import { MaterialUnderstandingSchema, PlanKnowledgeMapSchema } from "@/lib/knowledge-map/schema";
import { CanonicalLearnerProfileSchema } from "@/lib/personalization/canonical-profile-schema";
import { CanonicalPreferredMethodIdsSchema } from "@/lib/personalization/preferred-method-schema";
import { SESSION_ARCHITECTURE_VERSIONS } from "@/lib/session-generation/architecture";
import { StudyRouteSchema } from "@/lib/study-route/schema";
import { NORMAL_STUDY_DURATION_LEVELS } from "@/lib/study-route/duration-levels";

export const MAX_GENERATED_PLAN_SESSIONS = 14;
// Generated curriculum stays capped above. Runtime-only verification sessions
// may add at most one evidence check for each generated session.
export const MAX_RUNTIME_PLAN_SESSIONS = MAX_GENERATED_PLAN_SESSIONS * 2;

export const MaterialInputSchema = z.object({
  id: z.string().uuid(),
  name: z.string().trim().min(1).max(180),
  mimeType: z.string().trim().min(1).max(100),
  sizeBytes: z.number().int().min(1).max(10 * 1024 * 1024),
  textContent: z.string().max(288_000).nullable(),
  processingStatus: z.literal("ready"),
  understanding: MaterialUnderstandingSchema.nullable().optional(),
});

export const StoredMaterialSchema = MaterialInputSchema.extend({
  textContent: z.null(),
});

// A placement question and its options are generated by YOVA, shown to the
// learner, and then echoed back with the learner's answer so the plan
// generator can see what was already checked. Both directions must allow the
// same lengths: a question that is valid to display but too long to send back
// fails plan generation after the learner has already answered it.
export const DIAGNOSTIC_QUESTION_MAX_LENGTH = 500;
export const DIAGNOSTIC_OPTION_MAX_LENGTH = 180;

export const DiagnosticResponseSchema = z.object({
  questionId: z.string().uuid().optional(),
  topicId: z.string().uuid().optional(),
  question: z.string().trim().min(3).max(DIAGNOSTIC_QUESTION_MAX_LENGTH),
  answer: z.string().trim().min(1).max(DIAGNOSTIC_OPTION_MAX_LENGTH),
  evaluation: z.enum(["correct", "incorrect", "self_report"]),
});

export const PlanDiagnosticQuestionSchema = z.object({
  id: z.string().uuid(),
  topicId: z.string().uuid(),
  prompt: z.string().trim().min(12).max(DIAGNOSTIC_QUESTION_MAX_LENGTH),
  options: z.array(z.string().trim().min(1).max(DIAGNOSTIC_OPTION_MAX_LENGTH)).min(3).max(4),
  correctAnswer: z.string().trim().min(1).max(DIAGNOSTIC_OPTION_MAX_LENGTH),
});

export const PlanDiagnosticPreparationResponseSchema = z.object({
  knowledgeMap: PlanKnowledgeMapSchema,
  questions: z.array(PlanDiagnosticQuestionSchema).min(1).max(8),
  generation: z.object({
    requestId: z.string().uuid(),
    durationMs: z.number().int().nonnegative(),
    mode: z.enum(["preview", "openai", "system"]),
  }),
});

export const PlanGenerationRequestSchema = z.object({
  intent: z.enum(["plan", "study_now"]).default("plan"),
  learningIntent: z.enum(["learn", "study"]),
  goal: z.string().trim().min(10).max(600),
  startingContext: z.string().trim().max(800).optional(),
  materialMode: z.enum(["upload", "none"]),
  materials: z.array(MaterialInputSchema).max(5),
  studyMode: z.enum(["inside", "outside"]),
  deadline: z.string().datetime({ offset: true }).nullable().default(null),
  timeZone: z.string().trim().min(1).max(80).refine((value) => {
    try {
      new Intl.DateTimeFormat("en-US", { timeZone: value }).format();
      return true;
    } catch {
      return false;
    }
  }, "Use a valid time zone."),
  // Work products such as essays and projects do not always need an academic
  // knowledge check before YOVA can organize a useful plan.
  diagnosticResponses: z.array(DiagnosticResponseSchema).max(12),
  availability: z.array(z.object({
    day: z.string().trim().min(1).max(20),
    window: z.string().trim().min(1).max(40),
    minutes: z.number().int().min(5).max(180),
  })).min(1).max(14),
  profileSummary: z.string().trim().min(10).max(1_600),
  /**
   * An explicit one-session learner choice from the server-generated eligible
   * alternatives. The server recomputes eligibility; this identifier is never
   * sufficient authority on its own.
   */
  methodChoice: z.object({
    methodId: z.enum(CORE_METHOD_IDS),
  }).strict().optional(),
  /**
   * Request-local Method Library choices for the browser-only development
   * preview. The generation route rejects this field on every cloud request.
   */
  previewPreferredMethodIds: CanonicalPreferredMethodIdsSchema.optional(),
  /**
   * Browser-preview-only structured profile. Cloud generation rejects this
   * field and instead loads the authenticated account's canonical profile.
   */
  previewCanonicalProfile: CanonicalLearnerProfileSchema.optional(),
  knowledgeMap: PlanKnowledgeMapSchema.optional(),
  mapCorrection: z.string().trim().max(800).optional(),
}).superRefine((value, context) => {
  if (value.materialMode === "upload" && value.materials.length === 0) {
    context.addIssue({ code: "custom", path: ["materials"], message: "Add at least one material or choose no materials." });
  }
  if (value.materialMode === "none" && value.materials.length > 0) {
    context.addIssue({ code: "custom", path: ["materials"], message: "Materials must be empty when no materials is selected." });
  }
  if (value.intent === "study_now" && value.availability.length !== 1) {
    context.addIssue({
      code: "custom",
      path: ["availability"],
      message: "A focused Study Now request must provide exactly one current availability maximum.",
    });
  }
  if (value.intent !== "study_now" && value.methodChoice) {
    context.addIssue({
      code: "custom",
      path: ["methodChoice"],
      message: "A direct method choice currently applies only to one focused Study Now session.",
    });
  }
});

export const GeneratedSessionDraftSchema = z.object({
  title: z.string().trim().min(3).max(LEARNING_TITLE_CHARACTER_LIMIT),
  objective: z.string().trim().min(10).max(280),
  method: z.string().trim().min(3).max(80),
  methodReason: z.string().trim().min(10).max(280).describe(
    "Plain-language reason grounded in the task or current knowledge. It may mention a reported preference as tentative context, but must never claim a fixed learning style, brain type, diagnosis, or that the learner learns best in one way.",
  ),
  scheduledFor: z.string().datetime({ offset: true }),
  estimatedMinutes: z.number().int().min(5).max(180),
  amountLabel: z.string().trim().min(3).max(100),
  learningMode: z.enum(["learn", "study"]).describe(
    "Use learn when the session's first job is building a new mental model or procedure. Use study when its first job is retrieving, applying, practicing, assessing, or repairing knowledge already encountered. Every multi-session learn-first plan must later include at least one study session.",
  ),
  topicIds: z.array(z.string().uuid()).min(1).max(6),
  contentTargets: z.array(z.string().trim().min(5).max(180)).min(1).max(6),
  completionEvidence: z.array(z.string().trim().min(8).max(220).describe(
    "Observable evidence produced by the learner. Start with an active verb such as Explain, Solve, Apply, Classify, Compare, Construct, Draft, Recall, or Demonstrate. Never define completion as reading, reviewing, watching, exposure, or time spent.",
  )).min(1).max(4),
});

export const GeneratedPlanDraftSchema = z.object({
  title: z.string().trim().min(3).max(LEARNING_TITLE_CHARACTER_LIMIT),
  topic: z.string().trim().min(3).max(180),
  kind: z.enum(["test", "topic", "course", "book", "skill"]),
  deadline: z.string().datetime({ offset: true }).nullable(),
  rationale: z.string().trim().min(20).max(900).describe(
    "Explain the plan sequence using the goal, starting knowledge, time, and tentative delivery preferences. Never claim a fixed learning style, brain type, diagnosis, or that the learner learns best in one way.",
  ),
  deferredTopics: z.array(z.object({
    topicId: z.string().uuid(),
    reason: z.string().trim().min(8).max(300),
  })).max(40),
  sessions: z.array(GeneratedSessionDraftSchema).min(1).max(MAX_GENERATED_PLAN_SESSIONS),
});

/**
 * The planning model owns learner-facing content and sequencing, not method
 * selection. Keeping this provider-only schema separate prevents a generated
 * label or rationale from becoming an accidental routing input. Code adds the
 * compatibility method fields before the draft reaches the rest of the app.
 */
export const ProviderGeneratedSessionDraftSchema = GeneratedSessionDraftSchema.omit({
  method: true,
  methodReason: true,
});

export const ProviderGeneratedPlanDraftSchema = GeneratedPlanDraftSchema.extend({
  sessions: z.array(ProviderGeneratedSessionDraftSchema).min(1).max(MAX_GENERATED_PLAN_SESSIONS),
});

export const LearningPlanSchema = z.object({
  id: z.string().min(1),
  learningItemId: z.string().min(1),
  title: z.string().min(1),
  topic: z.string().min(1),
  kind: z.enum(["test", "topic", "course", "book", "skill"]),
  deadline: z.string().datetime({ offset: true }).nullable(),
  status: z.enum(["draft", "active", "completed", "archived"]),
  sourceMode: z.enum(["user_materials", "yova_generated"]),
  studyMode: z.enum(["inside_yova", "outside_yova"]),
  learningIntent: z.enum(["learn", "study"]),
  creationIntent: z.enum(["plan", "study_now"]).default("plan"),
  sessionArchitectureVersion: z.enum(SESSION_ARCHITECTURE_VERSIONS).default("filled_teaching_v1"),
  rationale: z.string().min(1),
  createdAt: z.string().datetime({ offset: true }),
  knowledgeMap: PlanKnowledgeMapSchema.optional(),
  materials: z.array(StoredMaterialSchema).max(5),
  sessions: z.array(z.object({
    id: z.string().min(1),
    sequence: z.number().int().positive(),
    title: z.string().min(1),
    objective: z.string().min(1),
    method: z.string().min(1),
    methodReason: z.string().min(1),
    scheduledFor: z.string().datetime({ offset: true }),
    estimatedMinutes: z.number().int().min(5).max(180),
    amountLabel: z.string().min(1),
    learningMode: z.enum(["learn", "study"]),
    topicIds: z.array(z.string().uuid()).default([]),
    contentTargets: z.array(z.string().min(1)).default([]),
    completionEvidence: z.array(z.string().min(1)).default([]),
    originSessionId: z.string().min(1).optional(),
    originalContentMinutes: z.number().int().positive().max(180).optional(),
    segmentIndex: z.number().int().positive().max(180).optional(),
    segmentCount: z.number().int().positive().max(180).optional(),
    status: z.enum(["ready", "upcoming", "complete", "skipped"]),
    studyRoute: StudyRouteSchema.optional(),
  })).min(1).max(MAX_RUNTIME_PLAN_SESSIONS),
});

export const GeneratedLearningPlanSchema = LearningPlanSchema.extend({
  sessions: LearningPlanSchema.shape.sessions.max(MAX_GENERATED_PLAN_SESSIONS),
});

export const PlanGenerationResponseSchema = z.object({
  plan: GeneratedLearningPlanSchema,
  generation: z.object({
    mode: z.enum(["preview", "openai", "system"]),
    model: z.string().nullable(),
    notice: z.string().nullable(),
    requestId: z.string().min(1),
    durationMs: z.number().int().nonnegative(),
    persistence: z.literal("draft"),
    draftReceipt: z.string().trim().min(1).max(512).nullable().optional(),
  }),
});

export const PlanActivationRequestSchema = z.object({
  plan: GeneratedLearningPlanSchema.extend({ status: z.literal("draft") }),
  generationRequest: PlanGenerationRequestSchema,
  draftReceipt: z.string().trim().min(1).max(512).nullable().default(null),
}).superRefine(({ plan, generationRequest }, context) => {
  if (plan.sessions.length > MAX_GENERATED_PLAN_SESSIONS) {
    context.addIssue({
      code: "custom",
      path: ["plan", "sessions"],
      message: `A generated plan may contain at most ${MAX_GENERATED_PLAN_SESSIONS} sessions.`,
    });
  }
  const expectedSourceMode = generationRequest.materialMode === "upload"
    ? "user_materials"
    : "yova_generated";
  const expectedStudyMode = generationRequest.studyMode === "outside"
    ? "outside_yova"
    : "inside_yova";
  const planMaterialIds = plan.materials.map((material) => material.id).sort();
  const requestMaterialIds = generationRequest.materials.map((material) => material.id).sort();
  const expectedLearningIntent = resolveLearningIntent({
    goal: generationRequest.goal,
    startingPoint: generationRequest.startingContext,
    diagnosticResponses: generationRequest.diagnosticResponses,
  }).intent;

  if (plan.sourceMode !== expectedSourceMode) {
    context.addIssue({ code: "custom", path: ["plan", "sourceMode"], message: "The draft source no longer matches the request." });
  }
  if (plan.studyMode !== expectedStudyMode) {
    context.addIssue({ code: "custom", path: ["plan", "studyMode"], message: "The draft study mode no longer matches the request." });
  }
  // Generation resolves the starting approach from the learner's latest
  // evidence on the server. Activation must repeat that same decision instead
  // of trusting the older client recommendation that was sent with the draft.
  if (plan.learningIntent !== expectedLearningIntent) {
    context.addIssue({ code: "custom", path: ["plan", "learningIntent"], message: "The draft starting approach no longer matches the request." });
  }
  if (plan.creationIntent !== generationRequest.intent) {
    context.addIssue({
      code: "custom",
      path: ["plan", "creationIntent"],
      message: "The draft creation flow no longer matches the generation request.",
    });
  }
  if (JSON.stringify(planMaterialIds) !== JSON.stringify(requestMaterialIds)) {
    context.addIssue({ code: "custom", path: ["plan", "materials"], message: "The draft materials no longer match the request." });
  }
  if (generationRequest.intent === "study_now" && plan.sessions.length !== 1) {
    context.addIssue({ code: "custom", path: ["plan", "sessions"], message: "A focused session must contain exactly one session." });
  }
  if (
    generationRequest.methodChoice
    && plan.sessions[0]?.studyRoute?.approach.primaryMethodId
      !== generationRequest.methodChoice.methodId
  ) {
    context.addIssue({
      code: "custom",
      path: ["plan", "sessions", 0, "studyRoute", "approach", "primaryMethodId"],
      message: "The focused-session route no longer matches the learner's reviewed method choice.",
    });
  }
  if (![plan.id, plan.learningItemId, ...plan.sessions.map((session) => session.id)].every((id) => z.string().uuid().safeParse(id).success)) {
    context.addIssue({ code: "custom", path: ["plan", "id"], message: "The draft contains an invalid identifier." });
  }
  const routedSessionCount = plan.sessions.filter((session) => Boolean(session.studyRoute)).length;
  if (routedSessionCount !== plan.sessions.length) {
    context.addIssue({
      code: "custom",
      path: ["plan", "sessions"],
      message: "Every newly generated session must carry its reviewed StudyRoute before activation.",
    });
  }
  const routeRevisionIds = new Set<string>();
  for (const [index, session] of plan.sessions.entries()) {
    const route = session.studyRoute;
    if (!route) continue;
    if (
      route.identity.planId !== plan.id
      || route.identity.sessionId !== session.id
    ) {
      context.addIssue({
        code: "custom",
        path: ["plan", "sessions", index, "studyRoute", "identity"],
        message: "The route identity does not belong to this plan session.",
      });
    }
    if (route.identity.lifecycleStatus !== "provisional") {
      context.addIssue({
        code: "custom",
        path: ["plan", "sessions", index, "studyRoute", "identity", "lifecycleStatus"],
        message: "Only a provisional route can be activated with a draft.",
      });
    }
    if (routeRevisionIds.has(route.identity.routeRevisionId)) {
      context.addIssue({
        code: "custom",
        path: ["plan", "sessions", index, "studyRoute", "identity", "routeRevisionId"],
        message: "Every plan session must have a distinct route revision.",
      });
    }
    routeRevisionIds.add(route.identity.routeRevisionId);
    const projectedLearningMode = route.approach.mode === "learn" ? "learn" : "study";
    if (
      projectedLearningMode !== session.learningMode
      || route.approach.executionEnvironment !== plan.studyMode
      || route.approach.visibleMethodName !== session.method
      || route.timing.activeMinutes !== session.estimatedMinutes
      || route.explanation.shortReason !== session.methodReason
    ) {
      context.addIssue({
        code: "custom",
        path: ["plan", "sessions", index, "studyRoute"],
        message: "The route no longer matches the learner-visible draft promise.",
      });
    }

    if (generationRequest.intent === "study_now") {
      const hardMaximumMinutes = generationRequest.availability[0]!.minutes;
      const normalDuration = NORMAL_STUDY_DURATION_LEVELS.some((minutes) => (
        minutes === route.timing.activeMinutes
      ));
      const currentDurationSource = ![
        "scheduled_review",
        "legacy_reconstruction",
      ].includes(route.timing.durationSource);
      const hasDurationTrace = route.provenance.ruleTrace.some((entry) => (
        entry.ruleId.startsWith("duration.")
      ));
      if (
        !normalDuration
        || route.timing.activeMinutes > hardMaximumMinutes
        || route.timing.hardMaximumMinutes !== hardMaximumMinutes
        || !currentDurationSource
        || !hasDurationTrace
      ) {
        context.addIssue({
          code: "custom",
          path: ["plan", "sessions", index, "studyRoute", "timing"],
          message: "The focused-session duration no longer matches its deterministic availability contract.",
        });
      }
    }
  }
});

export const PlanActivationResponseSchema = z.object({
  plan: GeneratedLearningPlanSchema.extend({ status: z.literal("active") }),
  activation: z.object({
    persistence: z.enum(["browser", "supabase"]),
    requestId: z.string().min(1),
  }),
});

/**
 * One bounded learner choice against the exact provisional route currently
 * shown in plan review. The expected revision prevents an older browser
 * response from overwriting a newer whole-plan draft.
 */
export const PlanDraftMethodChoiceSelectionSchema = z.object({
  sessionId: z.string().uuid(),
  expectedRouteRevisionId: z.string().uuid(),
  choiceScope: z.enum(["stored_alternative", "other_eligible_method"]).optional(),
  methodId: z.enum(CORE_METHOD_IDS).optional(),
  requestedMethod: z.string().trim().min(1).max(100).optional(),
}).strict().superRefine((selection, context) => {
  const other = selection.choiceScope === "other_eligible_method";
  if (other !== (selection.requestedMethod !== undefined)) {
    context.addIssue({
      code: "custom",
      path: ["requestedMethod"],
      message: "Other methods requires one bounded requested label.",
    });
  }
  if (other === (selection.methodId !== undefined)) {
    context.addIssue({
      code: "custom",
      path: ["methodId"],
      message: "A stored alternative and an Other-method label are mutually exclusive.",
    });
  }
});

export const PlanDraftMethodChoiceResponseSchema = z.object({
  plan: GeneratedLearningPlanSchema.extend({ status: z.literal("draft") }),
  draftReceipt: z.string().trim().min(1).max(512).nullable(),
  revision: z.object({
    status: z.enum(["updated", "unchanged"]),
    requestId: z.string().uuid(),
  }).strict(),
  methodRequestResolution: AgencyMethodRequestResolutionSchema.nullable().optional(),
}).strict();

export type PlanGenerationRequest = z.infer<typeof PlanGenerationRequestSchema>;
export type DiagnosticResponse = z.infer<typeof DiagnosticResponseSchema>;
export type PlanDiagnosticQuestion = z.infer<typeof PlanDiagnosticQuestionSchema>;
export type PlanDiagnosticPreparationResponse = z.infer<typeof PlanDiagnosticPreparationResponseSchema>;
export type GeneratedPlanDraft = z.infer<typeof GeneratedPlanDraftSchema>;
export type ProviderGeneratedPlanDraft = z.infer<typeof ProviderGeneratedPlanDraftSchema>;
export type PlanGenerationResponse = z.infer<typeof PlanGenerationResponseSchema>;
export type PlanActivationRequest = z.infer<typeof PlanActivationRequestSchema>;
export type PlanActivationResponse = z.infer<typeof PlanActivationResponseSchema>;
export type PlanDraftMethodChoiceSelection = z.infer<typeof PlanDraftMethodChoiceSelectionSchema>;
export type PlanDraftMethodChoiceResponse = z.infer<typeof PlanDraftMethodChoiceResponseSchema>;
