import type { Metadata } from "next";
import { TrustPage } from "@/components/trust-page";
import { PRIVACY_REQUEST_MAILTO, PUBLIC_CONTACT_EMAIL } from "@/lib/public-contact";

export const metadata: Metadata = {
  title: "Privacy Notice · YOVA",
  description: "How YOVA handles Study Profile, account, learning, material, tutor, and product data.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return <TrustPage eyebrow="PRIVACY NOTICE" title="Your learning data should be understandable." summary="This notice explains what YOVA stores across the public Study Profile and alpha, why it uses that information, and which controls are available." updated="August 17, 2026">
    <section><h2>1. What YOVA collects</h2><p>For the public YOVA Study Profile, YOVA stores the email you submit; your 12 assessment answers and resulting profile; the school level, energy window, and optional short response you provide; your communication consent choice; and whether you later join early access or volunteer for beta testing. YOVA may also store limited attribution such as campaign tags, traffic source, and the referring site&apos;s hostname, plus bounded funnel events such as the question number reached. Analytics events do not contain your email, answers, optional response, or private report token.</p><p>In the alpha, YOVA may store your account email and first name; onboarding preferences; learning goals, plans, and schedules; session completion, timing, quiz outcomes, confidence feedback, and interruptions; uploaded files and extracted text; tutor conversations; support requests; and limited technical or product events needed to operate and improve the product.</p><p>While a guided session is open, YOVA may save a small recovery checkpoint in your browser and, for signed-in accounts, in your YOVA account. It contains committed section progress, active study time, bounded learning evidence, completion feedback, and the session version needed to reopen the right lesson. If a repair step is waiting, it also keeps the concept and a bounded reference answer needed to show that step again. It does not contain an unfinished typed answer, tutor draft, or partially generated lesson text.</p><p>Technical error reports contain only bounded labels such as the affected product area, route, time, and an internal request reference. They do not contain your study material, tutor messages, typed answers, arbitrary error messages, or technical stack traces.</p><p>A typed free-response answer inside a guided learning session may be sent to OpenAI for a one-time formative comparison with YOVA&apos;s reference answer. YOVA does not save that session response in its database; it saves only the resulting concept outcome, confidence, and support context. The Study Profile itself is scored deterministically and does not require an OpenAI call.</p></section>
    <section><h2>2. How YOVA uses it</h2><p>YOVA uses Study Profile information to create and reopen your report, send the requested report email, operate the early-access list, honor an optional launch-updates choice, understand aggregate prelaunch demand, and improve future personalization. An unchecked communications option does not undo consent you previously granted; a separate unsubscribe process is used for revocation.</p><p>For the private alpha, YOVA uses information to authenticate you, save your work, create plans and activities, personalize the size and structure of future sessions, restore tutor context, prevent abuse, diagnose failures, provide support, and understand whether the core learning flow is useful.</p><p>YOVA asks about practical study behavior and support needs, not diagnoses. A Study Profile is an initial self-report, not a medical, neurological, psychological, or psychometric diagnosis. YOVA does not treat one answer or interruption as a permanent fact about your ability, and legacy diagnosed-condition answers are excluded from AI planning context.</p></section>
    <section><h2>3. AI and service providers</h2><p>Relevant instructions, learning context, bounded excerpts from source material, and a typed session answer submitted for formative feedback may be sent to OpenAI to generate plans, guided activities, explanations, questions, tutor replies, or an answer comparison. Uploaded material and learner responses are treated as untrusted content, not as instructions to the system.</p><p>YOVA currently relies on Supabase for authentication, database storage, and private file storage; OpenAI for private-alpha generation and formative answer checks; Vercel for application hosting; and, when enabled, Resend for transactional Study Profile report email. These providers process data as needed to deliver their part of the service.</p></section>
    <section><h2>4. Your controls</h2><p>The Study Profile marketing option is separate, explicit, and unchecked by default. Joining the early-access list or expressing beta interest uses the email already submitted and does not create an account. Each report link is a private bearer link: anyone with the link can view that report, so do not post it publicly.</p><p>Inside <strong>You</strong>, the Reset learning data control removes your learner profile, goals, plans, results, tutor conversations, analytics events, technical error reports, and private uploaded materials. Your login identity remains so you can sign in again. For privacy questions, or to request deletion of an account or public Study Profile record, email <a href={PRIVACY_REQUEST_MAILTO}>{PUBLIC_CONTACT_EMAIL}</a> with the subject “YOVA privacy or deletion request” and identify the email used.</p></section>
    <section><h2>5. Retention and security</h2><p>Study Profile leads and prior report versions are kept while reasonably needed to operate the prelaunch program, preserve the private reports requested by participants, learn from aggregate response patterns, or meet legal and security obligations, unless deletion is requested. Alpha learning data is kept while your account remains active unless you remove it. Limited support or security records may be retained when reasonably needed to resolve a request, prevent abuse, or meet legal obligations.</p><p>YOVA stores only a one-way hash of each Study Profile report token, keeps these public-funnel tables behind row-level security, and marks report pages not to be indexed. YOVA also uses account authentication, password hashing through its authentication provider, database ownership rules, private file storage, server-only credentials, validation, and rate limits. No online system can promise perfect security.</p></section>
    <section><h2>6. Age and changes</h2><p>YOVA is intended for people age 13 or older. If you are under the age of majority where you live, use YOVA only with permission from a parent or legal guardian. This notice may change as YOVA develops; the updated date at the top will change when it does.</p></section>
  </TrustPage>;
}
