-- A browser-held draft receipt proves that the plan was generated by YOVA,
-- but only the application server can verify that receipt. Close the remaining
-- database bypass with a short-lived, server-minted capability over the exact
-- active-plan JSONB payload, authenticated account, plan, and draft-receipt
-- issuance epoch. The consumed row is also the durable exact replay receipt
-- for an activation whose HTTP response was lost.

create table public.plan_activation_permits (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id uuid not null,
  payload_digest bytea not null,
  receipt_issued_at timestamptz not null,
  issued_at timestamptz not null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  saved_plan_id uuid,
  constraint plan_activation_permits_exact_payload_unique
    unique (user_id, plan_id, payload_digest),
  constraint plan_activation_permits_digest_check
    check (pg_catalog.octet_length(payload_digest) = 32),
  constraint plan_activation_permits_fixed_ttl_check
    check (expires_at = issued_at + interval '5 minutes'),
  constraint plan_activation_permits_receipt_window_check check (
    receipt_issued_at >= issued_at - interval '24 hours'
    and receipt_issued_at <= issued_at + interval '1 minute'
  ),
  constraint plan_activation_permits_outcome_check check (
    (consumed_at is null and saved_plan_id is null)
    or (
      consumed_at is not null
      and consumed_at >= issued_at
      and saved_plan_id = plan_id
    )
  )
);

create index plan_activation_permits_expiry_idx
on public.plan_activation_permits(expires_at);

create index plan_activation_permits_receipt_epoch_idx
on public.plan_activation_permits(receipt_issued_at)
where consumed_at is not null;

-- No PostgREST role may inspect or mutate the permit store directly. The
-- service role receives only the narrow mint and cleanup RPCs; transaction-
-- local database helpers use the table through their SECURITY DEFINER owners.
alter table public.plan_activation_permits enable row level security;
revoke all on table public.plan_activation_permits
from public, anon, authenticated, service_role;

-- Reset's historical boundary was retained only through the two-hour signed-
-- upload capability window. Draft receipts can live for 24 hours, so preserve
-- the same reset epoch for that longer authentication window plus the maximum
-- accepted one-minute receipt clock skew, without extending
-- compatibility_writes_blocked_until or the material-upload embargo itself.
alter table public.private_learning_data_reset_boundaries
add column plan_activation_epoch_expires_at timestamptz;

update public.private_learning_data_reset_boundaries as boundary
set plan_activation_epoch_expires_at = greatest(
  boundary.compatibility_writes_blocked_until,
  boundary.reset_completed_at + interval '24 hours 1 minute'
);

alter table public.private_learning_data_reset_boundaries
alter column plan_activation_epoch_expires_at set not null;

alter table public.private_learning_data_reset_boundaries
add constraint private_reset_plan_activation_epoch_check check (
  plan_activation_epoch_expires_at
    >= reset_completed_at + interval '24 hours 1 minute'
);

create or replace function public.guard_plan_activation_reset_epoch_v1()
returns trigger
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    -- The scheduled service cleanup historically deletes this row when the
    -- shorter upload embargo ends. Keep only that cleanup from erasing the
    -- receipt epoch early. Authenticated account deletion still removes the
    -- row immediately, and supported staging RPCs remain governed by the
    -- unchanged compatibility_writes_blocked_until value.
    if auth.role() = 'service_role'
      and old.plan_activation_epoch_expires_at > pg_catalog.clock_timestamp() then
      return null;
    end if;
    return old;
  end if;

  new.plan_activation_epoch_expires_at := greatest(
    coalesce(
      new.plan_activation_epoch_expires_at,
      new.reset_completed_at + interval '24 hours 1 minute'
    ),
    new.reset_completed_at + interval '24 hours 1 minute'
  );
  return new;
end;
$$;

revoke all on function public.guard_plan_activation_reset_epoch_v1()
from public, anon, authenticated, service_role;

create trigger private_reset_plan_activation_epoch_v1
before insert or update of reset_completed_at or delete
on public.private_learning_data_reset_boundaries
for each row execute function public.guard_plan_activation_reset_epoch_v1();

create or replace function public.mint_plan_activation_permit_v1(
  payload jsonb,
  requested_user_id uuid,
  draft_receipt_issued_at timestamptz
)
returns uuid
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  requested_plan_id uuid;
  requested_payload_text text;
  requested_payload_digest bytea;
  effective_issued_at timestamptz;
  latest_reset_completed_at timestamptz;
  existing_permit public.plan_activation_permits%rowtype;
  minted_permit_id uuid;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_service_role_required';
  end if;

  if requested_user_id is null or draft_receipt_issued_at is null then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_receipt_epoch_invalid';
  end if;

  if pg_catalog.jsonb_typeof(payload) is distinct from 'object'
    or pg_catalog.jsonb_typeof(payload -> 'sessions') is distinct from 'array' then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_payload_invalid';
  end if;
  if pg_catalog.jsonb_array_length(payload -> 'sessions') not between 1 and 14 then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_payload_invalid';
  end if;

  requested_payload_text := payload::text;
  if pg_catalog.octet_length(requested_payload_text) > 8388608 then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_payload_too_large';
  end if;

  begin
    requested_plan_id := nullif(payload ->> 'id', '')::uuid;
  exception when invalid_text_representation then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_plan_id_invalid';
  end;
  if requested_plan_id is null then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_plan_id_invalid';
  end if;

  -- Share the account-level ordering used by reset, deletion, plan writes and
  -- every route-aware mutation. Receipt and reset epochs are checked only
  -- after this lock, so Reset cannot land between authorization and mint.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('yova_learning_data'),
    pg_catalog.hashtext(requested_user_id::text)
  );

  effective_issued_at := pg_catalog.clock_timestamp();
  if draft_receipt_issued_at < effective_issued_at - interval '24 hours'
    or draft_receipt_issued_at > effective_issued_at + interval '1 minute' then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_receipt_epoch_invalid';
  end if;

  perform auth_user.id
  from auth.users as auth_user
  where auth_user.id = requested_user_id;
  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'plan_activation_permit_user_not_found';
  end if;

  select boundary.reset_completed_at
  into latest_reset_completed_at
  from public.private_learning_data_reset_boundaries as boundary
  where boundary.user_id = requested_user_id;
  -- Receipt verification admits at most one minute of positive clock skew.
  -- Quarantining that same interval prevents a receipt actually signed before
  -- Reset from appearing newer only because the app clock was ahead of SQL.
  if found and draft_receipt_issued_at
      <= latest_reset_completed_at + interval '1 minute' then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_predates_reset';
  end if;

  -- UUIDs are fixed-width, separators cannot occur in either UUID, and the
  -- canonical JSONB text is the final component. The receipt epoch is encoded
  -- as integer microseconds so the digest is independent of session timezone.
  requested_payload_digest := extensions.digest(
    pg_catalog.convert_to(
      'yova.plan_activation_permit.v2|'
        || requested_user_id::text || '|'
        || requested_plan_id::text || '|'
        || ((extract(epoch from draft_receipt_issued_at) * 1000000)::bigint)::text || '|'
        || requested_payload_text,
      'UTF8'
    ),
    'sha256'
  );

  -- An unconsumed capability has no authority after five minutes. Consumed
  -- outcomes remain through the maximum signed-receipt lifetime so a lost
  -- response can replay exactly, then become cleanup-eligible.
  delete from public.plan_activation_permits as stale_permit
  where stale_permit.user_id = requested_user_id
    and (
      (
        stale_permit.consumed_at is null
        and stale_permit.expires_at <= effective_issued_at
      )
      or (
        stale_permit.consumed_at is not null
        and stale_permit.receipt_issued_at
          <= effective_issued_at - interval '24 hours'
      )
    );

  select permit.*
  into existing_permit
  from public.plan_activation_permits as permit
  where permit.user_id = requested_user_id
    and permit.plan_id = requested_plan_id
    and permit.payload_digest = requested_payload_digest
  for update;
  if found then
    -- The exact live capability or exact durable outcome is idempotent. Its
    -- TTL is never extended, and a consumed outcome is never replaced.
    return existing_permit.id;
  end if;

  insert into public.plan_activation_permits (
    user_id,
    plan_id,
    payload_digest,
    receipt_issued_at,
    issued_at,
    expires_at
  ) values (
    requested_user_id,
    requested_plan_id,
    requested_payload_digest,
    draft_receipt_issued_at,
    effective_issued_at,
    effective_issued_at + interval '5 minutes'
  )
  on conflict (user_id, plan_id, payload_digest) do nothing
  returning id into minted_permit_id;

  if minted_permit_id is null then
    select permit.id
    into minted_permit_id
    from public.plan_activation_permits as permit
    where permit.user_id = requested_user_id
      and permit.plan_id = requested_plan_id
      and permit.payload_digest = requested_payload_digest;
  end if;
  if minted_permit_id is null then
    raise exception using
      errcode = '40001',
      message = 'plan_activation_permit_mint_conflict';
  end if;

  return minted_permit_id;
end;
$$;

revoke all on function public.mint_plan_activation_permit_v1(jsonb, uuid, timestamptz)
from public, anon, authenticated, service_role;
grant execute on function public.mint_plan_activation_permit_v1(jsonb, uuid, timestamptz)
to service_role;

-- Bounded hygiene for users who never return after a permit expires. Only
-- capabilities with no remaining authority and consumed outcomes beyond the
-- maximum signed-receipt lifetime are eligible.
create or replace function public.cleanup_plan_activation_permits_v1(
  requested_limit integer default 500
)
returns integer
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_service_role_required';
  end if;
  if requested_limit is null or requested_limit not between 1 and 2000 then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_cleanup_limit_invalid';
  end if;

  with cleanup_candidates as (
    select permit.id
    from public.plan_activation_permits as permit
    where (
      permit.consumed_at is null
      and permit.expires_at <= pg_catalog.clock_timestamp()
    ) or (
      permit.consumed_at is not null
      and permit.receipt_issued_at
        <= pg_catalog.clock_timestamp() - interval '24 hours'
    )
    order by permit.expires_at, permit.id
    for update skip locked
    limit requested_limit
  ), deleted as (
    delete from public.plan_activation_permits as permit
    using cleanup_candidates as candidate
    where permit.id = candidate.id
    returning permit.id
  )
  select pg_catalog.count(*)::integer
  into deleted_count
  from deleted;

  return deleted_count;
end;
$$;

revoke all on function public.cleanup_plan_activation_permits_v1(integer)
from public, anon, authenticated, service_role;
grant execute on function public.cleanup_plan_activation_permits_v1(integer)
to service_role;

-- Route-introduction guards may call this only from a database-owned trigger.
-- A GUC is not authority by itself: malformed values fail closed and the
-- matching private capability must still be unconsumed, live, and newer than
-- the latest completed Reset epoch.
create or replace function public.current_plan_activation_permit_matches_v1(
  requested_user_id uuid,
  requested_plan_id uuid
)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  configured_permit_id_text text := pg_catalog.current_setting(
    'yova.plan_activation_permit_id',
    true
  );
  configured_permit_id uuid;
begin
  if requested_user_id is null
    or requested_plan_id is null
    or nullif(configured_permit_id_text, '') is null then
    return false;
  end if;

  begin
    configured_permit_id := configured_permit_id_text::uuid;
  exception when invalid_text_representation then
    return false;
  end;

  return exists (
    select 1
    from public.plan_activation_permits as permit
    where permit.id = configured_permit_id
      and permit.user_id = requested_user_id
      and permit.plan_id = requested_plan_id
      and permit.consumed_at is null
      and permit.saved_plan_id is null
      and permit.expires_at > pg_catalog.clock_timestamp()
      and permit.receipt_issued_at
        >= pg_catalog.clock_timestamp() - interval '24 hours'
      and permit.receipt_issued_at
        <= pg_catalog.clock_timestamp() + interval '1 minute'
      and not exists (
        select 1
        from public.private_learning_data_reset_boundaries as boundary
        where boundary.user_id = requested_user_id
          and permit.receipt_issued_at
            <= boundary.reset_completed_at + interval '1 minute'
      )
  );
end;
$$;

revoke all on function public.current_plan_activation_permit_matches_v1(uuid, uuid)
from public, anon, authenticated, service_role;

-- Preserve the mature Reset body, but make permit invalidation the outermost
-- account-locked operation. Its existing account lock is transaction-level
-- and safely reentrant when the private delegate takes it again.
alter function public.reset_yova_learning_data()
rename to reset_yova_learning_data_without_plan_activation_permits_v1;

revoke all on function public.reset_yova_learning_data_without_plan_activation_permits_v1()
from public, anon, authenticated, service_role;

create or replace function public.reset_yova_learning_data()
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception using
      errcode = '42501',
      message = 'Authentication is required.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('yova_learning_data'),
    pg_catalog.hashtext(current_user_id::text)
  );

  delete from public.plan_activation_permits as permit
  where permit.user_id = current_user_id;

  return public.reset_yova_learning_data_without_plan_activation_permits_v1();
end;
$$;

revoke all on function public.reset_yova_learning_data()
from public, anon, authenticated, service_role;
grant execute on function public.reset_yova_learning_data()
to authenticated;

-- Preserve the hardened route-aware transaction exactly as deployed, but
-- make its old browser-callable signature private. This forward-only cutover
-- must be applied before the application begins passing the permit argument.
alter function public.save_generated_plan_with_routes(jsonb)
rename to save_generated_plan_with_routes_without_activation_permit_v1;

revoke all on function public.save_generated_plan_with_routes_without_activation_permit_v1(jsonb)
from public, anon, authenticated, service_role;

create or replace function public.save_generated_plan_with_routes(
  payload jsonb,
  activation_permit_id uuid
)
returns uuid
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  requested_plan_id uuid;
  requested_payload_text text;
  requested_payload_digest bytea;
  effective_now timestamptz;
  latest_reset_completed_at timestamptz;
  locked_permit public.plan_activation_permits%rowtype;
  delegated_saved_plan_id uuid;
begin
  if current_user_id is null then
    raise exception using
      errcode = '28000',
      message = 'plan_activation_authentication_required';
  end if;

  if activation_permit_id is null
    or pg_catalog.jsonb_typeof(payload) is distinct from 'object'
    or pg_catalog.jsonb_typeof(payload -> 'sessions') is distinct from 'array' then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_invalid';
  end if;
  if pg_catalog.jsonb_array_length(payload -> 'sessions') not between 1 and 14 then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_invalid';
  end if;

  requested_payload_text := payload::text;
  if pg_catalog.octet_length(requested_payload_text) > 8388608 then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_payload_too_large';
  end if;

  begin
    requested_plan_id := nullif(payload ->> 'id', '')::uuid;
  exception when invalid_text_representation then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_plan_id_invalid';
  end;
  if requested_plan_id is null then
    raise exception using
      errcode = '22023',
      message = 'plan_activation_permit_plan_id_invalid';
  end if;

  -- Canonical learner lock before the permit row lock. Reset takes this same
  -- lock, deletes every permit, and records its epoch in the private delegate.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('yova_learning_data'),
    pg_catalog.hashtext(current_user_id::text)
  );

  select permit.*
  into locked_permit
  from public.plan_activation_permits as permit
  where permit.id = activation_permit_id
  for update;

  if not found
    or locked_permit.user_id is distinct from current_user_id
    or locked_permit.plan_id is distinct from requested_plan_id then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_invalid';
  end if;

  effective_now := pg_catalog.clock_timestamp();
  if locked_permit.receipt_issued_at
      < effective_now - interval '24 hours'
    or locked_permit.receipt_issued_at
      > effective_now + interval '1 minute' then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_receipt_epoch_invalid';
  end if;

  select boundary.reset_completed_at
  into latest_reset_completed_at
  from public.private_learning_data_reset_boundaries as boundary
  where boundary.user_id = current_user_id;
  if found
    and locked_permit.receipt_issued_at
      <= latest_reset_completed_at + interval '1 minute' then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_predates_reset';
  end if;

  requested_payload_digest := extensions.digest(
    pg_catalog.convert_to(
      'yova.plan_activation_permit.v2|'
        || current_user_id::text || '|'
        || requested_plan_id::text || '|'
        || ((extract(epoch from locked_permit.receipt_issued_at) * 1000000)::bigint)::text || '|'
        || requested_payload_text,
      'UTF8'
    ),
    'sha256'
  );
  if locked_permit.payload_digest is distinct from requested_payload_digest then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_invalid';
  end if;

  -- A consumed exact digest is the database receipt. Return its durable
  -- outcome without invoking the non-idempotent mature writer again.
  if locked_permit.consumed_at is not null then
    if locked_permit.saved_plan_id is distinct from requested_plan_id then
      raise exception using
        errcode = '55000',
        message = 'plan_activation_permit_outcome_invalid';
    end if;
    return locked_permit.saved_plan_id;
  end if;

  if locked_permit.saved_plan_id is not null
    or locked_permit.expires_at <= effective_now then
    raise exception using
      errcode = '42501',
      message = 'plan_activation_permit_invalid';
  end if;

  perform pg_catalog.set_config(
    'yova.plan_activation_permit_id',
    activation_permit_id::text,
    true
  );

  delegated_saved_plan_id := public.save_generated_plan_with_routes_without_activation_permit_v1(
    payload
  );

  if delegated_saved_plan_id is distinct from requested_plan_id then
    raise exception using
      errcode = '55000',
      message = 'plan_activation_saved_plan_mismatch';
  end if;

  update public.plan_activation_permits as consumed_permit
  set
    consumed_at = pg_catalog.clock_timestamp(),
    saved_plan_id = delegated_saved_plan_id
  where consumed_permit.id = activation_permit_id
    and consumed_permit.consumed_at is null
    and consumed_permit.saved_plan_id is null;
  if not found then
    raise exception using
      errcode = '40001',
      message = 'plan_activation_permit_consumption_conflict';
  end if;

  return delegated_saved_plan_id;
end;
$$;

revoke all on function public.save_generated_plan_with_routes(jsonb, uuid)
from public, anon, authenticated, service_role;
grant execute on function public.save_generated_plan_with_routes(jsonb, uuid)
to authenticated;

-- The one-argument writer was replaced in this migration. Refresh PostgREST's
-- function signature cache on commit so the coordinated application cutover
-- sees the new authenticated RPC immediately.
notify pgrst, 'reload schema';
