-- Require email ownership confirmation before a Study Profile lead joins the
-- YOVA waitlist. Raw confirmation tokens are generated by the application and
-- emailed to the learner. Only their SHA-256 hashes cross this database boundary.

alter table public.study_profile_leads
add column if not exists report_email_next_allowed_at timestamptz;

create table public.study_profile_waitlist_confirmations (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.study_profile_leads(id) on delete cascade,
  response_id uuid references public.study_profile_responses(id) on delete set null,
  visitor_id uuid,
  token_hash text unique check (
    token_hash is null or token_hash ~ '^[0-9a-f]{64}$'
  ),
  consumed_token_hash text unique check (
    consumed_token_hash is null or consumed_token_hash ~ '^[0-9a-f]{64}$'
  ),
  status text not null default 'pending' check (
    status in ('pending', 'confirmed', 'superseded', 'expired', 'delivery_failed')
  ),
  consent_copy_version text not null check (
    char_length(consent_copy_version) between 1 and 80
  ),
  consent_source text not null check (
    consent_source in ('landing', 'email_gate', 'report_cta')
  ),
  age_confirmed boolean not null check (age_confirmed),
  scoring_revision text not null check (
    scoring_revision in ('study_profile_scoring_v1', 'study_profile_scoring_v2')
  ),
  profile_model_version text not null check (
    char_length(profile_model_version) between 3 and 64
  ),
  traffic_source text check (
    traffic_source is null or char_length(traffic_source) <= 100
  ),
  referrer_host text check (
    referrer_host is null or char_length(referrer_host) <= 255
  ),
  utm_source text check (
    utm_source is null or char_length(utm_source) <= 100
  ),
  utm_medium text check (
    utm_medium is null or char_length(utm_medium) <= 100
  ),
  utm_campaign text check (
    utm_campaign is null or char_length(utm_campaign) <= 160
  ),
  utm_content text check (
    utm_content is null or char_length(utm_content) <= 160
  ),
  utm_term text check (
    utm_term is null or char_length(utm_term) <= 160
  ),
  requested_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  resend_after timestamptz not null default (now() + interval '15 minutes'),
  confirmed_at timestamptz,
  replay_expires_at timestamptz,
  delivery_status text not null default 'pending' check (
    delivery_status in ('pending', 'sent', 'failed')
  ),
  delivery_provider_message_id text check (
    delivery_provider_message_id is null
    or char_length(delivery_provider_message_id) <= 200
  ),
  delivery_last_attempted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint study_profile_waitlist_confirmation_lifecycle check (
    (
      status = 'pending'
      and token_hash is not null
      and consumed_token_hash is null
      and confirmed_at is null
      and replay_expires_at is null
      and expires_at > requested_at
      and resend_after > requested_at
    )
    or (
      status = 'confirmed'
      and token_hash is null
      and confirmed_at is not null
      and (
        (
          consumed_token_hash is not null
          and replay_expires_at > confirmed_at
        )
        or (
          consumed_token_hash is null
          and replay_expires_at is null
        )
      )
    )
    or (
      status in ('superseded', 'expired', 'delivery_failed')
      and token_hash is null
      and consumed_token_hash is null
      and confirmed_at is null
      and replay_expires_at is null
    )
  )
);

create index study_profile_waitlist_confirmations_pending_lead_idx
on public.study_profile_waitlist_confirmations (lead_id, requested_at desc)
where status = 'pending';

create index study_profile_waitlist_confirmations_report_state_idx
on public.study_profile_waitlist_confirmations (response_id, status, requested_at desc)
where response_id is not null and status in ('pending', 'confirmed');

create index study_profile_waitlist_confirmations_replay_cleanup_idx
on public.study_profile_waitlist_confirmations (lead_id, replay_expires_at)
where consumed_token_hash is not null;

-- A single rolling ledger caps all recipient-directed Study Profile email
-- reservations, including failed provider deliveries. This prevents report
-- submissions and confirmation resends from bypassing one another's limits.
create table public.study_profile_email_delivery_attempts (
  id bigint generated always as identity primary key,
  lead_id uuid not null references public.study_profile_leads(id) on delete cascade,
  response_id uuid references public.study_profile_responses(id) on delete cascade,
  confirmation_id uuid references public.study_profile_waitlist_confirmations(id) on delete cascade,
  delivery_kind text not null check (
    delivery_kind in ('report', 'waitlist_confirmation')
  ),
  reserved_at timestamptz not null default now(),

  constraint study_profile_email_delivery_attempt_target check (
    (
      delivery_kind = 'report'
      and response_id is not null
      and confirmation_id is null
    )
    or (
      delivery_kind = 'waitlist_confirmation'
      and response_id is null
      and confirmation_id is not null
    )
  )
);

create index study_profile_email_delivery_attempts_lead_time_idx
on public.study_profile_email_delivery_attempts (lead_id, reserved_at desc);

create trigger study_profile_waitlist_confirmations_set_updated_at
before update on public.study_profile_waitlist_confirmations
for each row execute function public.set_updated_at();

alter table public.study_profile_waitlist_confirmations enable row level security;
alter table public.study_profile_email_delivery_attempts enable row level security;

revoke all on table public.study_profile_waitlist_confirmations
from public, anon, authenticated;

revoke all on table public.study_profile_email_delivery_attempts
from public, anon, authenticated;

grant select, insert, update, delete
on table public.study_profile_waitlist_confirmations
to service_role;

grant select, insert, delete
on table public.study_profile_email_delivery_attempts
to service_role;

revoke all
on sequence public.study_profile_email_delivery_attempts_id_seq
from public, anon, authenticated;

grant usage, select
on sequence public.study_profile_email_delivery_attempts_id_seq
to service_role;

-- The application no longer uses the immediate-join RPCs. Remove their
-- service-role execution grants so a future caller cannot bypass confirmation.
revoke execute on function public.join_study_profile_waitlist(jsonb)
from service_role;

revoke execute on function public.join_study_profile_report_waitlist(jsonb)
from service_role;

create or replace function public.request_study_profile_waitlist_confirmation(payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  normalized_email text := lower(btrim(payload ->> 'email'));
  confirmation_hash text := lower(btrim(payload ->> 'confirmationTokenHash'));
  consent_version text := btrim(payload ->> 'consentCopyVersion');
  resolved_visitor_id uuid := (payload ->> 'visitorId')::uuid;
  resolved_lead_id uuid;
  resolved_confirmation_id uuid;
  existing_confirmation_id uuid;
  existing_resend_after timestamptz;
  daily_attempt_count bigint;
  earliest_daily_attempt timestamptz;
  latest_confirmation_attempt timestamptz;
  retry_after_seconds integer;
  already_joined boolean := false;
begin
  if normalized_email is null
    or char_length(normalized_email) not between 3 and 320
    or normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$'
  then
    raise exception 'A valid normalized email is required.';
  end if;

  if confirmation_hash is null or confirmation_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'A valid confirmation token hash is required.';
  end if;

  if consent_version is null or char_length(consent_version) not between 1 and 80 then
    raise exception 'A waitlist consent copy version is required.';
  end if;

  if payload -> 'ageConfirmed' is distinct from 'true'::jsonb then
    raise exception 'A 13-or-older affirmation is required.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(normalized_email));

  select id, waitlist_status = 'joined'
  into resolved_lead_id, already_joined
  from public.study_profile_leads
  where email_normalized = normalized_email
  for update;

  if resolved_lead_id is null then
    insert into public.study_profile_leads (email_normalized)
    values (normalized_email)
    on conflict (email_normalized) do nothing;

    -- save_study_profile_response can create this lead concurrently without
    -- taking the landing RPC's advisory lock. Re-read and lock the canonical
    -- row after the conflict-safe insert instead of risking a unique failure.
    select id, waitlist_status = 'joined'
    into resolved_lead_id, already_joined
    from public.study_profile_leads
    where email_normalized = normalized_email
    for update;

    if resolved_lead_id is null then
      raise exception 'The normalized Study Profile lead could not be resolved.';
    end if;
  end if;

  -- Keep cleanup bounded to the locked recipient. Public requests must never
  -- scan and update every expired replay receipt in the table.
  update public.study_profile_waitlist_confirmations
  set consumed_token_hash = null, replay_expires_at = null
  where lead_id = resolved_lead_id
    and status = 'confirmed'
    and consumed_token_hash is not null
    and replay_expires_at <= now();

  if already_joined then
    return jsonb_build_object(
      'state', 'joined',
      'shouldSend', false,
      'confirmationId', null,
      'email', null,
      'retryAfterSeconds', 0
    );
  end if;

  select id, resend_after
  into existing_confirmation_id, existing_resend_after
  from public.study_profile_waitlist_confirmations
  where lead_id = resolved_lead_id
    and status = 'pending'
    and expires_at > now()
  order by requested_at desc
  limit 1
  for update;

  if existing_confirmation_id is not null and existing_resend_after > now() then
    return jsonb_build_object(
      'state', 'pending',
      'shouldSend', false,
      'confirmationId', existing_confirmation_id,
      'email', normalized_email,
      'retryAfterSeconds', greatest(
        1,
        ceil(extract(epoch from (existing_resend_after - now())))::integer
      )
    );
  end if;

  select max(reserved_at)
  into latest_confirmation_attempt
  from public.study_profile_email_delivery_attempts
  where lead_id = resolved_lead_id
    and delivery_kind = 'waitlist_confirmation';

  if latest_confirmation_attempt > now() - interval '15 minutes' then
    return jsonb_build_object(
      'state', 'masked',
      'shouldSend', false,
      'confirmationId', null,
      'email', null,
      'retryAfterSeconds', greatest(
        1,
        ceil(extract(epoch from (
          latest_confirmation_attempt + interval '15 minutes' - now()
        )))::integer
      )
    );
  end if;

  select count(*), min(reserved_at)
  into daily_attempt_count, earliest_daily_attempt
  from public.study_profile_email_delivery_attempts
  where lead_id = resolved_lead_id
    and reserved_at > now() - interval '24 hours';

  if daily_attempt_count >= 5 then
    retry_after_seconds := least(
      86400,
      greatest(
        1,
        ceil(extract(epoch from (
          earliest_daily_attempt + interval '24 hours' - now()
        )))::integer
      )
    );
    return jsonb_build_object(
      'state', 'daily_cap',
      'shouldSend', false,
      'confirmationId', null,
      'email', null,
      'retryAfterSeconds', retry_after_seconds
    );
  end if;

  update public.study_profile_waitlist_confirmations
  set
    status = case when expires_at <= now() then 'expired' else 'superseded' end,
    token_hash = null
  where lead_id = resolved_lead_id and status = 'pending';

  insert into public.study_profile_waitlist_confirmations (
    lead_id,
    visitor_id,
    token_hash,
    consent_copy_version,
    consent_source,
    age_confirmed,
    scoring_revision,
    profile_model_version,
    traffic_source,
    referrer_host,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_content,
    utm_term
  ) values (
    resolved_lead_id,
    resolved_visitor_id,
    confirmation_hash,
    consent_version,
    'landing',
    true,
    'study_profile_scoring_v2',
    'profile_model_v1',
    nullif(btrim(payload #>> '{attribution,source}'), ''),
    nullif(btrim(payload #>> '{attribution,referrerHost}'), ''),
    nullif(btrim(payload #>> '{attribution,utmSource}'), ''),
    nullif(btrim(payload #>> '{attribution,utmMedium}'), ''),
    nullif(btrim(payload #>> '{attribution,utmCampaign}'), ''),
    nullif(btrim(payload #>> '{attribution,utmContent}'), ''),
    nullif(btrim(payload #>> '{attribution,utmTerm}'), '')
  ) returning id into resolved_confirmation_id;

  insert into public.study_profile_email_delivery_attempts (
    lead_id,
    confirmation_id,
    delivery_kind
  ) values (
    resolved_lead_id,
    resolved_confirmation_id,
    'waitlist_confirmation'
  );

  return jsonb_build_object(
    'state', 'pending',
    'shouldSend', true,
    'confirmationId', resolved_confirmation_id,
    'email', normalized_email,
    'retryAfterSeconds', 0
  );
end;
$$;

revoke all on function public.request_study_profile_waitlist_confirmation(jsonb)
from public, anon, authenticated;

grant execute on function public.request_study_profile_waitlist_confirmation(jsonb)
to service_role;

create or replace function public.request_study_profile_report_waitlist_confirmation(payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  report_hash text := lower(btrim(payload ->> 'reportTokenHash'));
  confirmation_hash text := lower(btrim(payload ->> 'confirmationTokenHash'));
  consent_version text := btrim(payload ->> 'consentCopyVersion');
  consent_source text := btrim(payload ->> 'consentSource');
  resolved_response_id uuid;
  resolved_lead_id uuid;
  resolved_email text;
  resolved_model_version text;
  resolved_scoring_revision text;
  resolved_confirmation_id uuid;
  existing_confirmation_id uuid;
  existing_resend_after timestamptz;
  daily_attempt_count bigint;
  earliest_daily_attempt timestamptz;
  latest_confirmation_attempt timestamptz;
  retry_after_seconds integer;
  already_joined boolean := false;
begin
  if report_hash is null or report_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'A valid report token hash is required.';
  end if;

  if confirmation_hash is null or confirmation_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'A valid confirmation token hash is required.';
  end if;

  if consent_version is null or char_length(consent_version) not between 1 and 80 then
    raise exception 'A waitlist consent copy version is required.';
  end if;

  if consent_source is null or consent_source not in ('email_gate', 'report_cta') then
    raise exception 'A supported report waitlist source is required.';
  end if;

  if payload -> 'ageConfirmed' is distinct from 'true'::jsonb then
    raise exception 'A 13-or-older affirmation is required.';
  end if;

  select
    response.id,
    response.lead_id,
    lead.email_normalized,
    response.profile_model_version,
    coalesce(
      nullif(btrim(response.profile_snapshot ->> 'scoringRevision'), ''),
      'study_profile_scoring_v1'
    )
  into
    resolved_response_id,
    resolved_lead_id,
    resolved_email,
    resolved_model_version,
    resolved_scoring_revision
  from public.study_profile_responses as response
  join public.study_profile_leads as lead on lead.id = response.lead_id
  where response.report_token_hash = report_hash;

  if resolved_response_id is null or resolved_lead_id is null then
    return null;
  end if;

  if resolved_scoring_revision not in (
    'study_profile_scoring_v1',
    'study_profile_scoring_v2'
  ) then
    raise exception 'The stored Study Profile scoring revision is not supported.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext(resolved_lead_id::text)
  );

  select waitlist_status = 'joined'
  into already_joined
  from public.study_profile_leads
  where id = resolved_lead_id
  for update;

  -- This recipient-scoped cleanup uses the replay cleanup index and happens
  -- only after the lead lock has serialized request activity for the address.
  update public.study_profile_waitlist_confirmations
  set consumed_token_hash = null, replay_expires_at = null
  where lead_id = resolved_lead_id
    and status = 'confirmed'
    and consumed_token_hash is not null
    and replay_expires_at <= now();

  if exists (
    select 1
    from public.study_profile_waitlist_confirmations
    where response_id = resolved_response_id
      and status = 'confirmed'
  ) then
    return jsonb_build_object(
      'state', 'joined',
      'shouldSend', false,
      'confirmationId', null,
      'email', null,
      'retryAfterSeconds', 0
    );
  end if;

  -- A lead may already be confirmed through a different report or the public
  -- landing form. Do not reveal that shared membership to a newly minted
  -- report bearer. This response remains in a generic accepted state.
  if already_joined then
    return jsonb_build_object(
      'state', 'masked',
      'shouldSend', false,
      'confirmationId', null,
      'email', null,
      'retryAfterSeconds', 0
    );
  end if;

  select id, resend_after
  into existing_confirmation_id, existing_resend_after
  from public.study_profile_waitlist_confirmations
  where response_id = resolved_response_id
    and status = 'pending'
    and expires_at > now()
  order by requested_at desc
  limit 1
  for update;

  if existing_confirmation_id is not null and existing_resend_after > now() then
    return jsonb_build_object(
      'state', 'pending',
      'shouldSend', false,
      'confirmationId', existing_confirmation_id,
      'email', resolved_email,
      'retryAfterSeconds', greatest(
        1,
        ceil(extract(epoch from (existing_resend_after - now())))::integer
      )
    );
  end if;

  select max(reserved_at)
  into latest_confirmation_attempt
  from public.study_profile_email_delivery_attempts
  where lead_id = resolved_lead_id
    and delivery_kind = 'waitlist_confirmation';

  if latest_confirmation_attempt > now() - interval '15 minutes' then
    return jsonb_build_object(
      'state', 'masked',
      'shouldSend', false,
      'confirmationId', null,
      'email', null,
      'retryAfterSeconds', greatest(
        1,
        ceil(extract(epoch from (
          latest_confirmation_attempt + interval '15 minutes' - now()
        )))::integer
      )
    );
  end if;

  select count(*), min(reserved_at)
  into daily_attempt_count, earliest_daily_attempt
  from public.study_profile_email_delivery_attempts
  where lead_id = resolved_lead_id
    and reserved_at > now() - interval '24 hours';

  if daily_attempt_count >= 5 then
    retry_after_seconds := least(
      86400,
      greatest(
        1,
        ceil(extract(epoch from (
          earliest_daily_attempt + interval '24 hours' - now()
        )))::integer
      )
    );
    return jsonb_build_object(
      'state', 'daily_cap',
      'shouldSend', false,
      'confirmationId', null,
      'email', null,
      'retryAfterSeconds', retry_after_seconds
    );
  end if;

  update public.study_profile_waitlist_confirmations
  set
    status = case when expires_at <= now() then 'expired' else 'superseded' end,
    token_hash = null
  where response_id = resolved_response_id and status = 'pending';

  insert into public.study_profile_waitlist_confirmations (
    lead_id,
    response_id,
    token_hash,
    consent_copy_version,
    consent_source,
    age_confirmed,
    scoring_revision,
    profile_model_version
  ) values (
    resolved_lead_id,
    resolved_response_id,
    confirmation_hash,
    consent_version,
    consent_source,
    true,
    resolved_scoring_revision,
    resolved_model_version
  ) returning id into resolved_confirmation_id;

  insert into public.study_profile_email_delivery_attempts (
    lead_id,
    confirmation_id,
    delivery_kind
  ) values (
    resolved_lead_id,
    resolved_confirmation_id,
    'waitlist_confirmation'
  );

  return jsonb_build_object(
    'state', 'pending',
    'shouldSend', true,
    'confirmationId', resolved_confirmation_id,
    'email', resolved_email,
    'retryAfterSeconds', 0
  );
end;
$$;

revoke all on function public.request_study_profile_report_waitlist_confirmation(jsonb)
from public, anon, authenticated;

grant execute on function public.request_study_profile_report_waitlist_confirmation(jsonb)
to service_role;

create or replace function public.mark_study_profile_waitlist_confirmation_delivery(payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  resolved_confirmation_id uuid := (payload ->> 'confirmationId')::uuid;
  resolved_delivery_status text := btrim(payload ->> 'deliveryStatus');
  resolved_provider_message_id text := nullif(btrim(payload ->> 'providerMessageId'), '');
  updated_count integer;
begin
  if resolved_delivery_status is null or resolved_delivery_status not in ('sent', 'failed') then
    raise exception 'A supported delivery status is required.';
  end if;

  if resolved_provider_message_id is not null
    and char_length(resolved_provider_message_id) > 200
  then
    raise exception 'The provider message id is too long.';
  end if;

  update public.study_profile_waitlist_confirmations
  set
    delivery_status = resolved_delivery_status,
    delivery_provider_message_id = resolved_provider_message_id,
    delivery_last_attempted_at = now(),
    status = case when resolved_delivery_status = 'failed' then 'delivery_failed' else status end,
    token_hash = case when resolved_delivery_status = 'failed' then null else token_hash end,
    expires_at = case when resolved_delivery_status = 'failed' then now() else expires_at end,
    resend_after = case when resolved_delivery_status = 'failed' then now() else resend_after end
  where id = resolved_confirmation_id and status = 'pending';

  get diagnostics updated_count = row_count;
  return jsonb_build_object('updated', updated_count = 1);
end;
$$;

revoke all on function public.mark_study_profile_waitlist_confirmation_delivery(jsonb)
from public, anon, authenticated;

grant execute on function public.mark_study_profile_waitlist_confirmation_delivery(jsonb)
to service_role;

create or replace function public.confirm_study_profile_waitlist(payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  confirmation_hash text := lower(btrim(payload ->> 'confirmationTokenHash'));
  resolved_lead_id uuid;
  resolved_confirmation public.study_profile_waitlist_confirmations%rowtype;
  already_joined boolean := false;
begin
  if confirmation_hash is null or confirmation_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'A valid confirmation token hash is required.';
  end if;

  -- Discover the lead without taking a row lock, then follow the same lock
  -- order as both request RPCs: lead first, confirmation second. Recheck the
  -- token after both locks so a concurrent resend cannot confirm a superseded
  -- credential.
  select lead_id
  into resolved_lead_id
  from public.study_profile_waitlist_confirmations
  where token_hash = confirmation_hash and status = 'pending';

  if resolved_lead_id is null then
    if exists (
      select 1
      from public.study_profile_waitlist_confirmations
      where consumed_token_hash = confirmation_hash
        and status = 'confirmed'
        and replay_expires_at > now()
    ) then
      return jsonb_build_object(
        'status', 'confirmed',
        'waitlistJoined', true,
        'newlyJoined', false
      );
    end if;
    return jsonb_build_object('status', 'invalid', 'waitlistJoined', false);
  end if;

  select waitlist_status = 'joined'
  into already_joined
  from public.study_profile_leads
  where id = resolved_lead_id
  for update;

  if already_joined is null then
    return jsonb_build_object('status', 'invalid', 'waitlistJoined', false);
  end if;

  select *
  into resolved_confirmation
  from public.study_profile_waitlist_confirmations
  where token_hash = confirmation_hash
    and status = 'pending'
    and lead_id = resolved_lead_id
  for update;

  if resolved_confirmation.id is null then
    if exists (
      select 1
      from public.study_profile_waitlist_confirmations
      where consumed_token_hash = confirmation_hash
        and status = 'confirmed'
        and replay_expires_at > now()
    ) then
      return jsonb_build_object(
        'status', 'confirmed',
        'waitlistJoined', true,
        'newlyJoined', false
      );
    end if;
    return jsonb_build_object('status', 'invalid', 'waitlistJoined', false);
  end if;

  if resolved_confirmation.expires_at <= now() then
    update public.study_profile_waitlist_confirmations
    set status = 'expired', token_hash = null
    where id = resolved_confirmation.id;
    return jsonb_build_object('status', 'expired', 'waitlistJoined', false);
  end if;

  if not already_joined then
    update public.study_profile_leads
    set
      waitlist_status = 'joined',
      waitlist_joined_at = now(),
      waitlist_consent_copy_version = resolved_confirmation.consent_copy_version,
      waitlist_consent_source = resolved_confirmation.consent_source
    where id = resolved_confirmation.lead_id;

    insert into public.study_profile_events (
      visitor_id,
      response_id,
      event_name,
      event_data,
      profile_model_version,
      traffic_source,
      referrer_host,
      utm_source,
      utm_medium,
      utm_campaign,
      utm_content,
      utm_term
    ) values (
      resolved_confirmation.visitor_id,
      resolved_confirmation.response_id,
      'study_profile_waitlist_joined',
      jsonb_build_object(
        'source', resolved_confirmation.consent_source,
        'scoringRevision', resolved_confirmation.scoring_revision,
        'doubleOptIn', true
      ),
      resolved_confirmation.profile_model_version,
      resolved_confirmation.traffic_source,
      resolved_confirmation.referrer_host,
      resolved_confirmation.utm_source,
      resolved_confirmation.utm_medium,
      resolved_confirmation.utm_campaign,
      resolved_confirmation.utm_content,
      resolved_confirmation.utm_term
    );
  end if;

  update public.study_profile_waitlist_confirmations
  set
    status = 'confirmed',
    token_hash = null,
    consumed_token_hash = confirmation_hash,
    confirmed_at = now(),
    replay_expires_at = least(
      resolved_confirmation.expires_at,
      now() + interval '15 minutes'
    )
  where id = resolved_confirmation.id;

  return jsonb_build_object(
    'status', 'confirmed',
    'waitlistJoined', true,
    'newlyJoined', not already_joined
  );
end;
$$;

revoke all on function public.confirm_study_profile_waitlist(jsonb)
from public, anon, authenticated;

grant execute on function public.confirm_study_profile_waitlist(jsonb)
to service_role;

create or replace function public.reserve_study_profile_report_email_delivery(payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  resolved_response_id uuid := (payload ->> 'responseId')::uuid;
  resolved_lead_id uuid;
  next_allowed_at timestamptz;
  daily_attempt_count bigint;
  earliest_daily_attempt timestamptz;
  retry_after_seconds integer;
begin
  select lead_id
  into resolved_lead_id
  from public.study_profile_responses
  where id = resolved_response_id;

  if resolved_lead_id is null then
    return null;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext(resolved_lead_id::text)
  );

  select report_email_next_allowed_at
  into next_allowed_at
  from public.study_profile_leads
  where id = resolved_lead_id
  for update;

  select count(*), min(reserved_at)
  into daily_attempt_count, earliest_daily_attempt
  from public.study_profile_email_delivery_attempts
  where lead_id = resolved_lead_id
    and reserved_at > now() - interval '24 hours';

  if daily_attempt_count >= 5 then
    retry_after_seconds := least(
      86400,
      greatest(
        1,
        ceil(extract(epoch from (
          earliest_daily_attempt + interval '24 hours' - now()
        )))::integer
      )
    );

    update public.study_profile_responses
    set
      email_delivery_status = 'skipped',
      email_last_attempted_at = now()
    where id = resolved_response_id;

    return jsonb_build_object(
      'allowed', false,
      'reason', 'daily_cap',
      'retryAfterSeconds', retry_after_seconds
    );
  end if;

  if next_allowed_at is null or next_allowed_at <= now() then
    insert into public.study_profile_email_delivery_attempts (
      lead_id,
      response_id,
      delivery_kind
    ) values (
      resolved_lead_id,
      resolved_response_id,
      'report'
    );

    update public.study_profile_leads
    set report_email_next_allowed_at = now() + interval '15 minutes'
    where id = resolved_lead_id;

    update public.study_profile_responses
    set email_last_attempted_at = now()
    where id = resolved_response_id;

    return jsonb_build_object(
      'allowed', true,
      'reason', null,
      'retryAfterSeconds', 0
    );
  end if;

  retry_after_seconds := greatest(
    1,
    ceil(extract(epoch from (next_allowed_at - now())))::integer
  );

  update public.study_profile_responses
  set
    email_delivery_status = 'skipped',
    email_last_attempted_at = now()
  where id = resolved_response_id;

  return jsonb_build_object(
    'allowed', false,
    'reason', 'cooldown',
    'retryAfterSeconds', retry_after_seconds
  );
end;
$$;

revoke all on function public.reserve_study_profile_report_email_delivery(jsonb)
from public, anon, authenticated;

grant execute on function public.reserve_study_profile_report_email_delivery(jsonb)
to service_role;

create or replace function public.study_profile_public_readiness_v1()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  with readiness as (
    select
      pg_catalog.to_regclass(
        'public.study_profile_waitlist_confirmations'
      ) is not null
      and (
        select count(*) = 11
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'study_profile_waitlist_confirmations'
          and column_name in (
            'token_hash',
            'consumed_token_hash',
            'status',
            'consent_copy_version',
            'consent_source',
            'age_confirmed',
            'expires_at',
            'resend_after',
            'confirmed_at',
            'replay_expires_at',
            'delivery_status'
          )
      )
      and pg_catalog.to_regclass(
        'public.study_profile_waitlist_confirmations_report_state_idx'
      ) is not null
      and pg_catalog.to_regclass(
        'public.study_profile_waitlist_confirmations_replay_cleanup_idx'
      ) is not null
      and coalesce((
        select relrowsecurity
        from pg_catalog.pg_class
        where oid = pg_catalog.to_regclass(
          'public.study_profile_waitlist_confirmations'
        )
      ), false) as pending_confirmation_columns,
      pg_catalog.to_regprocedure(
        'public.request_study_profile_waitlist_confirmation(jsonb)'
      ) is not null
      and pg_catalog.to_regprocedure(
        'public.request_study_profile_report_waitlist_confirmation(jsonb)'
      ) is not null
      and pg_catalog.to_regprocedure(
        'public.mark_study_profile_waitlist_confirmation_delivery(jsonb)'
      ) is not null
      and pg_catalog.to_regprocedure(
        'public.confirm_study_profile_waitlist(jsonb)'
      ) is not null
      and position(
        'daily_attempt_count >= 5' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0
      and position(
        'daily_attempt_count >= 5' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_report_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0
      and position(
        'interval ''24 hours''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0
      and position(
        'interval ''24 hours''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_report_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0
      and position(
        'delivery_kind = ''waitlist_confirmation''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0
      and position(
        'delivery_kind = ''waitlist_confirmation''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_report_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0
      and position(
        'interval ''15 minutes''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0
      and position(
        'interval ''15 minutes''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.request_study_profile_report_waitlist_confirmation(jsonb)'
          )
        ))
      ) > 0 as confirmation_rpcs,
      exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'study_profile_leads'
          and column_name = 'report_email_next_allowed_at'
      )
      and pg_catalog.to_regprocedure(
        'public.reserve_study_profile_report_email_delivery(jsonb)'
      ) is not null
      and pg_catalog.to_regclass(
        'public.study_profile_email_delivery_attempts'
      ) is not null
      and coalesce((
        select relrowsecurity
        from pg_catalog.pg_class
        where oid = pg_catalog.to_regclass(
          'public.study_profile_email_delivery_attempts'
        )
      ), false)
      and position(
        'daily_attempt_count >= 5' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.reserve_study_profile_report_email_delivery(jsonb)'
          )
        ))
      ) > 0
      and position(
        'interval ''24 hours''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.reserve_study_profile_report_email_delivery(jsonb)'
          )
        ))
      ) > 0
      and position(
        'interval ''15 minutes''' in pg_catalog.lower(pg_catalog.pg_get_functiondef(
          pg_catalog.to_regprocedure(
            'public.reserve_study_profile_report_email_delivery(jsonb)'
          )
        ))
      ) > 0 as report_email_cooldown,
      not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_waitlist_confirmations',
        'SELECT'
      )
      and not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_waitlist_confirmations',
        'INSERT'
      )
      and not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_waitlist_confirmations',
        'UPDATE'
      )
      and not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_waitlist_confirmations',
        'DELETE'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_waitlist_confirmations',
        'SELECT'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_waitlist_confirmations',
        'INSERT'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_waitlist_confirmations',
        'UPDATE'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_waitlist_confirmations',
        'DELETE'
      )
      and pg_catalog.has_table_privilege(
        'service_role',
        'public.study_profile_waitlist_confirmations',
        'SELECT'
      )
      and pg_catalog.has_table_privilege(
        'service_role',
        'public.study_profile_waitlist_confirmations',
        'INSERT'
      )
      and pg_catalog.has_table_privilege(
        'service_role',
        'public.study_profile_waitlist_confirmations',
        'UPDATE'
      )
      and pg_catalog.has_table_privilege(
        'service_role',
        'public.study_profile_waitlist_confirmations',
        'DELETE'
      )
      and not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_email_delivery_attempts',
        'SELECT'
      )
      and not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_email_delivery_attempts',
        'INSERT'
      )
      and not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_email_delivery_attempts',
        'UPDATE'
      )
      and not pg_catalog.has_table_privilege(
        'anon',
        'public.study_profile_email_delivery_attempts',
        'DELETE'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_email_delivery_attempts',
        'SELECT'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_email_delivery_attempts',
        'INSERT'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_email_delivery_attempts',
        'UPDATE'
      )
      and not pg_catalog.has_table_privilege(
        'authenticated',
        'public.study_profile_email_delivery_attempts',
        'DELETE'
      )
      and pg_catalog.has_table_privilege(
        'service_role',
        'public.study_profile_email_delivery_attempts',
        'SELECT'
      )
      and pg_catalog.has_table_privilege(
        'service_role',
        'public.study_profile_email_delivery_attempts',
        'INSERT'
      )
      and pg_catalog.has_table_privilege(
        'service_role',
        'public.study_profile_email_delivery_attempts',
        'DELETE'
      )
      and not pg_catalog.has_sequence_privilege(
        'anon',
        'public.study_profile_email_delivery_attempts_id_seq',
        'USAGE'
      )
      and not pg_catalog.has_sequence_privilege(
        'authenticated',
        'public.study_profile_email_delivery_attempts_id_seq',
        'USAGE'
      )
      and pg_catalog.has_sequence_privilege(
        'service_role',
        'public.study_profile_email_delivery_attempts_id_seq',
        'USAGE'
      )
      and pg_catalog.has_sequence_privilege(
        'service_role',
        'public.study_profile_email_delivery_attempts_id_seq',
        'SELECT'
      )
      and not pg_catalog.has_function_privilege(
        'anon',
        'public.request_study_profile_waitlist_confirmation(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'authenticated',
        'public.request_study_profile_waitlist_confirmation(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'anon',
        'public.request_study_profile_report_waitlist_confirmation(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'authenticated',
        'public.request_study_profile_report_waitlist_confirmation(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'anon',
        'public.mark_study_profile_waitlist_confirmation_delivery(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'authenticated',
        'public.mark_study_profile_waitlist_confirmation_delivery(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'anon',
        'public.confirm_study_profile_waitlist(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'authenticated',
        'public.confirm_study_profile_waitlist(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'anon',
        'public.reserve_study_profile_report_email_delivery(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'authenticated',
        'public.reserve_study_profile_report_email_delivery(jsonb)',
        'EXECUTE'
      )
      and pg_catalog.has_function_privilege(
        'service_role',
        'public.request_study_profile_waitlist_confirmation(jsonb)',
        'EXECUTE'
      )
      and pg_catalog.has_function_privilege(
        'service_role',
        'public.request_study_profile_report_waitlist_confirmation(jsonb)',
        'EXECUTE'
      )
      and pg_catalog.has_function_privilege(
        'service_role',
        'public.mark_study_profile_waitlist_confirmation_delivery(jsonb)',
        'EXECUTE'
      )
      and pg_catalog.has_function_privilege(
        'service_role',
        'public.confirm_study_profile_waitlist(jsonb)',
        'EXECUTE'
      )
      and pg_catalog.has_function_privilege(
        'service_role',
        'public.reserve_study_profile_report_email_delivery(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'anon',
        'public.join_study_profile_waitlist(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'authenticated',
        'public.join_study_profile_waitlist(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'anon',
        'public.join_study_profile_report_waitlist(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'authenticated',
        'public.join_study_profile_report_waitlist(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'service_role',
        'public.join_study_profile_waitlist(jsonb)',
        'EXECUTE'
      )
      and not pg_catalog.has_function_privilege(
        'service_role',
        'public.join_study_profile_report_waitlist(jsonb)',
        'EXECUTE'
      ) as service_role_boundary
  )
  select jsonb_build_object(
    'contractVersion', '202608310002',
    'ready',
      pending_confirmation_columns
      and confirmation_rpcs
      and report_email_cooldown
      and service_role_boundary,
    'pendingConfirmationColumns', pending_confirmation_columns,
    'confirmationRpcs', confirmation_rpcs,
    'reportEmailCooldown', report_email_cooldown,
    'serviceRoleBoundary', service_role_boundary
  )
  from readiness;
$$;

revoke all on function public.study_profile_public_readiness_v1()
from public, anon, authenticated;

grant execute on function public.study_profile_public_readiness_v1()
to service_role;
